language: python
dist: xenial

addons:
  postgresql: "9.6"

matrix:
  include:
   - env: TOXENV=py35-dj20-sqlite
     python: 3.5
   - env: TOXENV=py36-dj20-sqlite
     python: 3.6
   - env: TOXENV=py35-dj21-sqlite
     python: 3.5
   - env: TOXENV=py36-dj21-sqlite
     python: 3.6
   - env: TOXENV=py37-dj21-sqlite
     python: 3.7
   - env: TOXENV=py35-dj22-sqlite
     python: 3.5
   - env: TOXENV=py36-dj22-sqlite
     python: 3.6
   - env: TOXENV=py37-dj22-sqlite
     python: 3.7
   - env: TOXENV=py35-dj20-postgres
     python: 3.5
   - env: TOXENV=py36-dj20-postgres
     python: 3.6
   - env: TOXENV=py35-dj21-postgres
     python: 3.5
   - env: TOXENV=py36-dj21-postgres
     python: 3.6
   - env: TOXENV=py37-dj21-postgres
     python: 3.7
   - env: TOXENV=py35-dj22-postgres
     python: 3.5
   - env: TOXENV=py36-dj22-postgres
     python: 3.6
   - env: TOXENV=py37-dj22-postgres
     python: 3.7

install:
  - pip install tox
  - createdb modelcluster

script:
  tox
